modular/stack-pr

.github/workflows/release.yml, pyproject.toml, src/stack_pr/__main__.py, src/stack_pr/cli.py
Add a github action that can be used to upload to pypi.
Make the version number dynamic so now the tag determines the version number of the package so we can use the github release system to cut releases. These should automatically get uploaded to pypi when we tag and release here.
Also add a file I missed in the last commit.
=> [pypi] Add github action for pypi publishing

src/stack_pr/__main__.py, src/stack_pr/cli.py
Issue 1:
--target bug, "/main" was hardcoded
Issue 2:
Relative imports are hard to work with. E.g.
~/stack_pr
~/my_repo
In my repo, I can not python -m call into ~/stack_pr, because I can not go up in the directory hierarhy, I think.
So my approach is:
1. remove relative imports
2. add src root into PYTHONPATH
then within ~/my_repo I can do
> python /home/salex/stack-pr/src/stack_pr/cli.py submit --target my_base
=> fix relative imports and --target setting

src/stack_pr/cli.py
Implements enough of the [terminal hyperlink specification][1] to allow
us to include links to PRs, where they exist, in the terminal output.
This specification is implemented by several terminals, including:
- kitty
- wezterm
- iTerm2
- Alacritty
- Windows Terminal
- Konsole
- xterm.js (VS Code's backing terminal implementation)
See [this tracking repository][2] for a full listing.
The ECMA-48 specification requires that terminals that do not understand
the OSC-8 command code silently ignore it; in compliant terminals that
do not implement the hyperlink specification, users will simply observe
no changes to the output of `stack-pr`. For cases where outputting these
escape codes is still undesirable I have added a `--no-hyperlinks` flag.
[1]: …
=> Emit terminal hyperlinks

src/stack_pr/cli.py
Stacked PRs:
* __->__#21
--- --- ---
Fixes #15.
=> Add a None check for exc.stdout.

src/stack_pr/cli.py
GitHub lets you check if a PR is actually mergeable via the `gh` CLI by
retrieving the `mergeStateStatus` field. This field has a bunch of
values (see the [API documentation][1] linked below), but the one we care
about is `CLEAN`, indicating that the PR has no merge conflicts and has
passed PR checks.
I'd like to eventually add this information to `stack-pr view`, but it will
require some extra piping, and will slow down the command due to the
extra network request.
1: https://docs.github.com/en/graphql/reference/enums#mergestatestatus
=> Check that the bottom PR is mergeable

src/stack_pr/cli.py
delete_remote_branches formatted remote
branch refs with an extra single quote
around each branch. These would never
match the branch strings stored in
stack entries, so remote branches would
never get deleted. This commit removes
the extra single quotes.
=> Fix delete_remote_branches

src/stack_pr/cli.py, src/stack_pr/git.py, src/stack_pr/shell_commands.py
For large or busy repositories, stack-pr commands can generate hundreds
of lines of output from Git subcommands being executed. Most of the time
these don't matter; the user doesn't care about them. This PR suppresses
them by default by redirecting stdout and stderr to
`subprocess.DEVNULL`. If this output is desired in a specific case, the
command-line flag `--verbose` (`-V`) can be used to avoid this
redirection.
=> Suppress subcommand output by default

src/stack_pr/cli.py, src/stack_pr/git.py, src/stack_pr/shell_commands.py
Stacked PRs:
* __->__#31
--- --- ---
=> Run black on sources.

README.md, src/stack_pr/cli.py
Stacked PRs:
* #33
* __->__#32
--- --- ---
The allows to have a local config to customize defaults for CL options.
Closes #22.
=> Add config files feature.

README.md, src/stack_pr/cli.py
Stacked PRs:
* __->__#33
--- --- ---
Closes #18.
=> Allow customizing branch names for branches stack-pr creates.

src/stack_pr/cli.py
Stacked PRs:
* __->__#42
--- --- ---
GitHub deletes the remote branch automatically when the PR is merged, so
we don't to explicitly do that. Trying to delete it currently results in
an error like this:
```
error: unable to delete 'ZolotukhinM/stack/1': remote ref does not exist
error: failed to push some refs to '...'
```
The code for deleting the branch has been sitting there for a long time,
but until a fix in #27 it used incorrect branch names.
=> Don't attempt to delete remote branch after a PR has landed.

.gitignore, README.md, src/stack_pr/cli.py
This PR adds the ability for someone to use $BRANCH in the branch_name_template which would correspond to the current branch name.
=> resolve $BRANCH as current branch name in branch_name_template

src/stack_pr/cli.py
Stacked PRs:
* __->__#49
--- --- ---
When validating whether a PR is mergeable on GitHub, sometimes the PR
will get stuck in an `UNKNOWN` merge state and block merging, even if
it's mergeable in the GitHub UI.
=> Allow merge state to be UNKNOWN

README.md
Stacked PRs:
* #61
* #60
* __->__#59
--- --- ---
Co-authored-by: Shay Nehmad <dude500@gmail.com>
=> Add docs for command line options.

src/stack_pr/cli.py
Stacked PRs:
* #61
* __->__#60
* #59
--- --- ---
Fixes #55.
Co-authored-by: Shay Nehmad <dude500@gmail.com>
=> Allow merging PRs with 'UNSTABLE' status on GH.

src/stack_pr/cli.py
Stacked PRs:
* __->__#68
--- --- ---
Before this change we incorrectly tried to rebase the bottom commit
which resulted in malformed state of the result.
=> Fix a bug in 'abandon' when the current branch is 'main'.

README.md, src/stack_pr/cli.py
This change adds the `--stash` or `-s` option to the `submit` command parser. If set, it will run `git stash save` before any commands in the normal `submit` workflow and, when done, it will run `git stash pop` to undo this mechanism.
=> Adds the option to stash uncommitted changes before submitting PRs

src/stack_pr/cli.py
Stacked PRs:
* #74
* #73
* __->__#72
--- --- ---
=> Only check 'args.stash' when 'submit' or 'export' is used

README.md, src/stack_pr/cli.py, tests/test_misc.py
Stacked PRs:
* #74
* __->__#73
* #72
--- --- ---
Previously the branch number was always at the end after `/`. This PR
generalizes it and allows it to be present anywhere in the template
under the placeholder "$ID".
Fixes #57.
=> Allow specifying the location for the branch number in the branch name template.

.github/workflows/check_tests.yml, src/stack_pr/git.py, tests/test_misc.py
Stacked PRs:
* __->__#74
* #73
* #72
--- --- ---
=> Add CI workflow for running unittests.
